# Generated by Django 3.1.4 on 2020-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultImage',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('related_image_id', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='result_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploaded_images/')),
            ],
        ),
    ]
